"""github_users

Revision ID: dee15dfb4ef5
Revises:
Create Date: 2022-01-13 13:32:59.570456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "dee15dfb4ef5"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_model",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=True),
        sa.Column("avatar_url", sa.String(length=512), nullable=True),
        sa.Column("type", sa.String(length=40), nullable=True),
        sa.Column("URL", sa.String(length=512), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_model_username"),
        "user_model",
        ["username"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_model_username"), table_name="user_model")
    op.drop_table("user_model")
    # ### end Alembic commands ###
